config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :phrases, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phrase.rb
class Phrase < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  
  def create 
    @phrase = Phrase.create(phrase_params)
    redirect_to root_path
  end

  private 

  def phrase_params
    params.require(:phrase).permit(:author, :sentence)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @phrase = Phrase.new
    @phrases = Phrase.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplestApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb

<div class="offset-1 col-10">
  <h1 class="text-center">We make phrases and then we display them</h1>
  <h4 class= "float-right">-Quiz 2</h4>
  <br />
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary btn-lg add-button " data-toggle="modal" data-target="#exampleModal">
    Add a new phrase
  </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= simple_form_for @phrase, url: phrases_path do |f| %>
        <div class="modal-body">
            <%= f.input :author %>
            <%= f.input :sentence %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit 'Create', class: 'btn btn-primary' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <% @phrases.each do |phrase| %>
        <div class="col-12 col-sm-4">
          <div class="fancy">
          <h3><%= phrase.sentence %></h3>
          <h5>- <%= phrase.author %></h5>
          </div>
        </div>
    <% end %>
  </div>

</div>